### PR TITLE
Update heketi package to version 5.0.0

### PR DESCRIPTION
**Pull request by obnoxxx**

### CODE REVIEW

**Comment by obnoxxx** [comment]
Not sure this works completely. It's my first attempt.
A scratch build worked: https://cbs.centos.org/koji/taskinfo?taskID=228534

**Review by raghavendra-talur — COMMENTED** [review]
LGTM

**Review by nixpanic — APPROVED** [review]
Thanks! Looks good to me. I'll wait for Jose's opinion as this probably is required for Fedora as well. It is best if the two sets of files can be kept in sync.

**Comment by obnoxxx** [comment]
@nixpanic right. fedora and centos are not in sync right now. I started looking at fedora pkg as well. but it seems approval and the stuff around it has changed since I last did fedora packaging, so I need to figure that out. ;-)

**Comment by jarrpa** [comment]
Overall the update seems fine, and it has been tested, so LGTM!

@nixpanic The Fedora packaging includes a build target for EPEL7. How does that interact with the CentOS Storage SIG packages?

**Comment by nixpanic** [comment]
There is no interaction between EPEL7 and packages in the CentOS Storage SIG. All packages in all CentOS SIGs are contained within CentOS. If any testing in the CentOS CI is need, or official CentOS VM/container images need to be produced, only CentOS (not Fedora EPEL) packages may be used.

Furthermore, GlusterFS is not in EPEL, so a heketi package there will be difficult to use.

**Comment by jarrpa** [comment]
> There is no interaction between EPEL7 and packages in the CentOS Storage SIG. All packages in all CentOS SIGs are contained within CentOS. If any testing in the CentOS CI is need, or official CentOS VM/container images need to be produced, only CentOS (not Fedora EPEL) packages may be used.

Ahh, okay. This is distinctly more CentOS-official, then. :)

> Furthermore, GlusterFS is not in EPEL, so a heketi package there will be difficult to use.

....oh! I should probably remove that build target, then. ;)

**Pull request merged**
